# Generated by Django 4.2.7 on 2025-12-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("document_upload", "Document Upload"),
                            ("document_view", "Document View"),
                            ("audio_conversion", "Audio Conversion"),
                            ("audio_play", "Audio Play"),
                            ("audio_download", "Audio Download"),
                            ("login", "Login"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional activity data"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name_plural": "User activities",
                "db_table": "user_activities",
                "ordering": ["-timestamp"],
            },
        ),
    ]
