# Generated by Django 4.2.7 on 2025-12-11 01:12

import audio.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AudioFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audio_file",
                    models.FileField(
                        blank=True, null=True, upload_to=audio.models.audio_upload_path
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, help_text="Audio duration in seconds", null=True
                    ),
                ),
                (
                    "voice_type",
                    models.CharField(
                        default="female",
                        help_text="Voice type used for TTS",
                        max_length=50,
                    ),
                ),
                (
                    "speech_rate",
                    models.FloatField(
                        default=1.0, help_text="Speech rate (0.5x to 2x)"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", help_text="Language code", max_length=5
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if conversion failed"
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, help_text="Celery task ID", max_length=255
                    ),
                ),
                ("download_count", models.IntegerField(default=0)),
                (
                    "generated_date",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "audio_files",
                "ordering": ["-generated_date"],
            },
        ),
    ]
