# Generated by Django 4.2.7 on 2025-12-11 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        ("audio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audio_files",
                to="documents.document",
            ),
        ),
        migrations.AddIndex(
            model_name="audiofile",
            index=models.Index(
                fields=["document", "-generated_date"],
                name="audio_files_documen_10dddd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="audiofile",
            index=models.Index(
                fields=["status", "-generated_date"],
                name="audio_files_status_4ec42b_idx",
            ),
        ),
    ]
